# Generated by Django 4.2.6 on 2024-09-28 08:20

from django.db import migrations, models
import utils.generate_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('s_code', models.CharField(default=utils.generate_code.generate_code, max_length=10, unique=True)),
                ('matirial', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teacher_profile_images')),
                ('phone', models.IntegerField(unique=True)),
                ('matirial', models.CharField(max_length=5, unique=True)),
                ('t_code', models.CharField(default=utils.generate_code.generate_code, max_length=8, unique=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
