# Generated by Django 4.2.6 on 2024-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0002_teacherprofile_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
