# Generated by Django 4.2.6 on 2024-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0003_teacherprofile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='matirial',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
