# Generated by Django 4.2.6 on 2024-09-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0004_teacherprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matirial',
            field=models.CharField(max_length=50),
        ),
    ]
