# Generated by Django 4.2.6 on 2024-09-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0007_rename_student_student_teacher_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matirial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matirial_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='matirial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_matirial', to='ecms_app.matirial'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='matirial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_matirial', to='ecms_app.matirial'),
        ),
    ]
