# Generated by Django 4.2.6 on 2024-09-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0008_matirial_alter_student_matirial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='matirial',
        ),
    ]
