# Generated by Django 4.2.6 on 2024-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0009_remove_student_matirial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matirial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
