# Generated by Django 4.2.6 on 2024-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0010_student_matirial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matirial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='matirial',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
