# Generated by Django 4.2.6 on 2024-09-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0011_alter_student_matirial_alter_teacherprofile_matirial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matirial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='matirial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_matirial', to='ecms_app.matirial'),
        ),
    ]
