# Generated by Django 4.2.6 on 2024-10-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecms_app', '0015_alter_teacherprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
