# Generated by Django 4.2.6 on 2024-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecms_app', '0016_alter_teacherprofile_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
